#include <suture/hook.h>

#include <stdlib.h>
#include <string.h>

#define ACC_PUBLIC 0x0001       // Declared public; may be accessed from outside its package.
#define ACC_PRIVATE 0x0002      // Declared private; accessible only within the defining class.
#define ACC_PROTECTED 0x0004    // Declared protected; may be accessed within subclasses.
#define ACC_STATIC 0x0008       // Declared static.
#define ACC_FINAL 0x0010        // Declared final; must not be overridden (§5.4.5).
#define ACC_SYNCHRONIZED 0x0020 // Declared synchronized; invocation is wrapped by a monitor use.
#define ACC_BRIDGE 0x0040       // A bridge method, generated by the compiler.
#define ACC_VARARGS 0x0080      // Declared with variable number of arguments.
#define ACC_NATIVE 0x0100       // Declared native; implemented in a language other than Java.
#define ACC_ABSTRACT 0x0400     // Declared abstract; no implementation is provided.
#define ACC_STRICT 0x0800       // Declared strictfp; floating-point mode is FP-strict.
#define ACC_SYNTHETIC 0x1000    // Declared synthetic; not present in the source code.

enum su_error su_hook_detour(const struct su_hook *hook, struct su_transform *transform, struct su_stream *stream) {
  u1 *attributes = NULL;

  const u2 attributes_offset = sizeof(u2) * 3;
  const u2 attributes_length = stream->length - attributes_offset;

  attributes = (u1 *)malloc(sizeof(u1) * attributes_length);
  if (attributes == NULL)
    return SU_MEMORY_ALLOCATION_FAILURE;

  memcpy(attributes, stream->buffer + attributes_offset, attributes_length);

  stream->cursor = 0;
  u2 flags, name_index, desc_index;

  enum su_error status = SU_OK;
  SU_TRY_CATCH(status, su_stream_r2(stream, &flags, 0), exit);
  SU_TRY_CATCH(status, su_stream_r2(stream, &name_index, 0), exit);
  SU_TRY_CATCH(status, su_stream_r2(stream, &desc_index, 0), exit);

  SU_FREE(stream->buffer);

  stream->length = 0;
  stream->cursor = 0;

  SU_TRY_CATCH(status, su_stream_w2(stream, flags | ACC_NATIVE, 0), exit);
  SU_TRY_CATCH(status, su_stream_w2(stream, name_index, 0), exit);
  SU_TRY_CATCH(status, su_stream_w2(stream, desc_index, 0), exit);
  SU_TRY_CATCH(status, su_stream_w2(stream, 0, 0), exit);

  struct su_stream *new_stream;
  SU_TRY_CATCH(status, su_add_method(transform, hook->original_name, hook->signature, ACC_PRIVATE | (flags & ACC_STATIC ? ACC_STATIC : ACC_FINAL), &new_stream), exit);
  SU_TRY_CATCH(status, su_stream_wn(new_stream, attributes, attributes_length, 0), exit);

exit:
  SU_FREE(attributes);
  return status;
}

char *su_hook_original_name(const char *name) {
  if (name == NULL)
    return NULL;

  const char *prefix = "__su_original__";
  const size_t length = strlen(prefix) + strlen(name);

  char *original_name = malloc(length + 1);
  if (original_name == NULL)
    return NULL;

  snprintf(original_name, length + 1, "%s%s", prefix, name);
  return original_name;
}