#include <suture/transform.h>

#include <suture.h>
#include <suture/stream.h>
#include <suture/types.h>

#include <assert.h>
#include <string.h>

#define CONSTANT_Class 7
#define CONSTANT_Fieldref 9
#define CONSTANT_Methodref 10
#define CONSTANT_InterfaceMethodref 11
#define CONSTANT_String 8
#define CONSTANT_Integer 3
#define CONSTANT_Float 4
#define CONSTANT_Long 5
#define CONSTANT_Double 6
#define CONSTANT_NameAndType 12
#define CONSTANT_Utf8 1
#define CONSTANT_MethodHandle 15
#define CONSTANT_MethodType 16
#define CONSTANT_InvokeDynamic 18

#define ACC_PUBLIC 0x0001       // Declared public; may be accessed from outside its package.
#define ACC_PRIVATE 0x0002      // Declared private; accessible only within the defining class.
#define ACC_PROTECTED 0x0004    // Declared protected; may be accessed within subclasses.
#define ACC_STATIC 0x0008       // Declared static.
#define ACC_FINAL 0x0010        // Declared final; must not be overridden (§5.4.5).
#define ACC_SYNCHRONIZED 0x0020 // Declared synchronized; invocation is wrapped by a monitor use.
#define ACC_BRIDGE 0x0040       // A bridge method, generated by the compiler.
#define ACC_VARARGS 0x0080      // Declared with variable number of arguments.
#define ACC_NATIVE 0x0100       // Declared native; implemented in a language other than Java.
#define ACC_ABSTRACT 0x0400     // Declared abstract; no implementation is provided.
#define ACC_STRICT 0x0800       // Declared strictfp; floating-point mode is FP-strict.
#define ACC_SYNTHETIC 0x1000    // Declared synthetic; not present in the source code.

void JNICALL su_transform_class_file_load_hook(jvmtiEnv *jvmti, JNIEnv *jni, jclass class_being_redefined, jobject loader, const char *name, jobject protection_domain, jint class_data_len, const unsigned char *class_data, jint *new_class_data_len, unsigned char **new_class_data) {
  struct su_env *env = NULL;
  enum su_error status = SU_OK;

  if (JVM_INVOKE(jvmti, GetEnvironmentLocalStorage, (void **)&env) != JVMTI_ERROR_NONE)
    return;

  unsigned char *old_bytes = (u1 *)malloc(sizeof(unsigned char) * class_data_len);
  assert(old_bytes != NULL && "failed to allocate memory for the old bytes");

  memcpy(old_bytes, class_data, class_data_len);

  struct su_transform transform = { 0 };
  SU_TRY_CATCH(status, su_transform_init(&transform, (u1 *)class_data, (u2)class_data_len), exit);

  for (u2 i = 0; i < env->hooks_count; i++) {
    struct su_hook *hook = &env->hooks[i];
    if (strcmp(name, hook->class_name) != 0)
      continue;

    hook->original_bytes = old_bytes;
    hook->original_length = class_data_len;

    u1 *attributes = NULL;
    u2 attributes_length = 0;
    u2 flags = 0;

    const u2 methods_count = transform.methods_count;
    for (u2 j = 0; j < methods_count; j++) {
      const struct su_method *method = &transform.methods[j];
      if (strcmp(hook->name, method->name) != 0 || strcmp(hook->signature, method->desc) != 0)
        continue;

      struct su_stream *stream = &method->chunk->stream;
      flags = (stream->buffer[0] << 8) | stream->buffer[1];

      const u2 name_index = (stream->buffer[2] << 8) | stream->buffer[3];
      const u2 desc_index = (stream->buffer[4] << 8) | stream->buffer[5];

      attributes_length = (stream->length - 6);
      attributes = malloc(sizeof(u1) * attributes_length);
      assert(attributes != NULL && "failed to allocate memory for attributes");

      memcpy(attributes, stream->buffer + 6, attributes_length);

      SU_FREE(stream->buffer);

      stream->buffer = NULL;
      stream->length = 0;
      stream->cursor = 0;

      su_stream_w2(stream, flags | ACC_NATIVE, 0);
      su_stream_w2(stream, name_index, 0);
      su_stream_w2(stream, desc_index, 0);
      su_stream_w2(stream, 0, 0);

      break;
    }

    struct su_stream *original_stream = su_add_method(&transform, hook->original_name, hook->signature, ACC_PRIVATE | ACC_FINAL);
    su_stream_wn(original_stream, attributes, attributes_length, 0);

    u1 *t_buffer;
    u2 t_length;

    {
      su_transform_build(&transform, &t_buffer, &t_length);

      unsigned char *jvmti_buffer = NULL;
      JVM_TRY_CATCH(status, JVM_INVOKE(jvmti, Allocate, t_length, &jvmti_buffer), JVMTI_ERROR_NONE, SU_JVM_GENERIC_FAILURE, exit);

      memcpy(jvmti_buffer, t_buffer, t_length);

      (*new_class_data) = jvmti_buffer;
      (*new_class_data_len) = t_length;
    }

    free(t_buffer);

    su_transform_dispose(&transform);
  }

exit:
  env->error = status;
}

enum su_error su_transform_init(struct su_transform *transform, u1 *buffer, const u2 buffer_length) {
  if (transform == NULL || buffer == NULL || buffer_length == 0)
    return SU_MISSING_REQUIRED_PARAMETERS;

  enum su_error status = SU_OK;

  memset((void *)transform, 0, sizeof(struct su_transform));
  transform->chunks = NULL;

  struct su_stream stream = {
    .buffer = buffer,
    .length = buffer_length,
    .cursor = 0,
    .chunk = 0
  };

  u4 magic;
  SU_TRY_CATCH(status, su_stream_r4(&stream, &magic, 0), exit);

  if (magic != 0xCAFEBABE)
    return SU_JVM_INVALID_CLASS_MAGIC;

  stream.cursor += sizeof(u2) * 2;

  SU_TRY_CATCH(status, su_stream_chunk(&stream, &transform->chunks, NULL), exit);
  SU_TRY_CATCH(status, su_stream_r2(&stream, &transform->constant_pool_count, 0), exit);

  transform->constant_pool = calloc(transform->constant_pool_count, sizeof(void *));
  assert(transform->constant_pool != NULL && "failed to allocate memory for constant pool");

  for (u2 i = 1; i < transform->constant_pool_count; i++) {
    u1 tag;
    SU_TRY_CATCH(status, su_stream_r1(&stream, &tag, 0), exit);

    switch (tag) {
    case CONSTANT_Class:
    case CONSTANT_String:
    case CONSTANT_MethodType:
      stream.cursor += sizeof(u2);
      break;
    case CONSTANT_Fieldref:
    case CONSTANT_Methodref:
    case CONSTANT_InterfaceMethodref:
    case CONSTANT_NameAndType:
    case CONSTANT_InvokeDynamic:
      stream.cursor += sizeof(u2) * 2;
      break;
    case CONSTANT_Integer:
    case CONSTANT_Float:
      stream.cursor += sizeof(u4);
      break;
    case CONSTANT_Long:
    case CONSTANT_Double:
      stream.cursor += sizeof(u4) * 2;
      i++;
      break;
    case CONSTANT_Utf8: {
      u2 length;
      SU_TRY_CATCH(status, su_stream_r2(&stream, &length, 0), exit);

      char *string = malloc(sizeof(char) * (length + 1));
      assert(string != NULL && "failed to allocate memory for string");

      SU_TRY_CATCH(status, su_stream_rn(&stream, (u1 *)string, length, 0), exit);
      string[length] = '\0';

      transform->constant_pool[i] = string;
    } break;
    case CONSTANT_MethodHandle:
      stream.cursor += sizeof(u1) + sizeof(u2);
      break;
    default:
      status = SU_JVM_INVALID_CONSTANT_POOL;
      goto exit;
    }
  }

  SU_TRY_CATCH(status, su_stream_chunk(&stream, &transform->chunks, NULL), exit);

  u2 interfaces_count;
  SU_TRY_CATCH(status, su_stream_r2(&stream, &interfaces_count, sizeof(u2) * 3), exit);

  stream.cursor += sizeof(u2) * interfaces_count;

  u2 fields_count;
  SU_TRY_CATCH(status, su_stream_r2(&stream, &fields_count, 0), exit);

  for (u2 i = 0; i < fields_count; i++) {
    u2 attributes_count;
    SU_TRY_CATCH(status, su_stream_r2(&stream, &attributes_count, sizeof(u2) * 3), exit);

    for (u2 j = 0; j < attributes_count; j++) {
      u4 attributes_length;
      SU_TRY_CATCH(status, su_stream_r4(&stream, &attributes_length, sizeof(u2)), exit);

      stream.cursor += attributes_length;
    }
  }

  SU_TRY_CATCH(status, su_stream_chunk(&stream, &transform->chunks, NULL), exit);
  SU_TRY_CATCH(status, su_stream_r2(&stream, &transform->methods_count, 0), exit);

  transform->methods = calloc(transform->methods_count, sizeof(struct su_method));
  assert(transform->methods != NULL && "failed to allocate memory for methods");

  for (u2 i = 0; i < transform->methods_count; i++) {
    u2 name_index;
    SU_TRY_CATCH(status, su_stream_r2(&stream, &name_index, sizeof(u2)), exit);

    u2 desc_index;
    SU_TRY_CATCH(status, su_stream_r2(&stream, &desc_index, 0), exit);

    u2 attributes_count;
    SU_TRY_CATCH(status, su_stream_r2(&stream, &attributes_count, 0), exit);

    for (u2 j = 0; j < attributes_count; j++) {
      u4 attributes_length;
      SU_TRY_CATCH(status, su_stream_r4(&stream, &attributes_length, sizeof(u2)), exit);

      stream.cursor += attributes_length;
    }

    struct su_chunk *current_chunk = NULL;
    SU_TRY_CATCH(status, su_stream_chunk(&stream, &transform->chunks, &current_chunk), exit);

    transform->methods[i].name = strdup((char *)transform->constant_pool[name_index]);
    transform->methods[i].desc = strdup((char *)transform->constant_pool[desc_index]);
    transform->methods[i].chunk = current_chunk;
  }

  u2 attributes_count;
  SU_TRY_CATCH(status, su_stream_r2(&stream, &attributes_count, 0), exit);

  for (u2 j = 0; j < attributes_count; j++) {
    u4 attributes_length;
    SU_TRY_CATCH(status, su_stream_r4(&stream, &attributes_length, sizeof(u2)), exit);

    stream.cursor += attributes_length;
  }

  SU_TRY_CATCH(status, su_stream_chunk(&stream, &transform->chunks, NULL), exit);

  if (stream.cursor < stream.length)
    return SU_STREAM_UNFINISHED_READ;

exit:
  return status;
}

u2 su_const_add_utf8(struct su_transform *transform, const char *utf8) {
  struct su_stream *const_pool_stream = &transform->chunks->next->stream;
  su_stream_w1(const_pool_stream, CONSTANT_Utf8, 0);

  const u2 length = (u2)strlen(utf8);
  su_stream_w2(const_pool_stream, length, 0);
  su_stream_wn(const_pool_stream, (void *)utf8, length, 0);

  transform->constant_pool = realloc(transform->constant_pool, sizeof(void *) * (transform->constant_pool_count + 1));
  transform->constant_pool[transform->constant_pool_count] = NULL;

  return transform->constant_pool_count++;
}

struct su_stream *su_add_method(struct su_transform *transform, const char *name, const char *desc, const u2 access_flags) {
  const u2 name_index = su_const_add_utf8(transform, name);
  const u2 desc_index = su_const_add_utf8(transform, desc);

  transform->methods = realloc(transform->methods, sizeof(struct su_method) * (transform->methods_count + 1));
  assert(transform->methods != NULL && "failed to allocate memory for the methods");

  struct su_chunk *method_chunk = (struct su_chunk *)malloc(sizeof(struct su_chunk));
  assert(method_chunk != NULL && "failed to allocate memory for the method chunk");

  memset(method_chunk, 0, sizeof(*method_chunk));

  su_stream_w2(&method_chunk->stream, access_flags, 0);
  su_stream_w2(&method_chunk->stream, name_index, 0);
  su_stream_w2(&method_chunk->stream, desc_index, 0);

  struct su_chunk *last_chunk = transform->methods[transform->methods_count - 1].chunk;
  method_chunk->prev = last_chunk;
  method_chunk->next = last_chunk->next;

  if (last_chunk->next != NULL)
    last_chunk->next->prev = method_chunk;

  last_chunk->next = method_chunk;

  transform->methods[transform->methods_count] = (struct su_method){
    .name = strdup(name),
    .desc = strdup(desc),
    .chunk = method_chunk
  };

  transform->methods_count++;
  return &method_chunk->stream;
}

enum su_error su_transform_build(const struct su_transform *transform, u1 **buffer, u2 *buffer_length) {
  if (transform == NULL || buffer == NULL || buffer_length == NULL)
    return SU_MISSING_REQUIRED_PARAMETERS;

  u2 sz = 0;
  u1 *buff = NULL;

  struct su_chunk *const_pool_chunk = transform->chunks->next;
  const_pool_chunk->stream.cursor = 0;
  su_stream_w2(&const_pool_chunk->stream, transform->constant_pool_count, 0);

  struct su_chunk *first_method_chunk = transform->methods->chunk;
  first_method_chunk->stream.cursor = 0;
  su_stream_w2(&first_method_chunk->stream, transform->methods_count, 0);

  const struct su_chunk *chunk = transform->chunks;
  while (chunk != NULL) {
    const u2 chunk_length = chunk->stream.length;

    buff = realloc(buff, sz + chunk_length);
    memcpy(buff + sz, chunk->stream.buffer, chunk_length);

    sz += chunk_length;
    chunk = chunk->next;
  }

  (*buffer) = buff;
  (*buffer_length) = sz;
  return SU_OK;
}

void su_transform_dispose(struct su_transform *transform) {
  if (transform == NULL)
    return;

  for (u2 i = 0; i < transform->constant_pool_count; i++)
    SU_FREE(transform->constant_pool[i]);
  SU_FREE(transform->constant_pool);

  struct su_chunk *chunk = transform->chunks;
  while (chunk != NULL) {
    struct su_chunk *next = chunk->next;

    SU_FREE(chunk->stream.buffer);
    SU_FREE(chunk);

    chunk = next;
  }
  transform->chunks = NULL;

  for (u2 i = 0; i < transform->methods_count; i++) {
    SU_FREE(transform->methods[i].name);
    SU_FREE(transform->methods[i].desc);
  }
  SU_FREE(transform->methods);
}